### ISSUE TITLE
加一个未使用的连接多久没使用后close掉会更完美

### ISSUE THREAD

**Issue by hel2o** [456vv/vconnpool#1]
当池的连接很大时 比如上6W多个 若是一直保护这些长期未使用的连接会很占资源 要是能加一个未使用连接超时关闭就更好了

**Comment by 456vv** [comment]
可以设置“空闲连接最大数量”和“连接最大数量”；使用过连接不会全部回收，除非你没有设置空闲连接数量。如果是设置超时关闭空闲连接，最后若全部超时都关闭了，空闲连接为0。待需要之时如何保证快速交换数据？

**Comment by 456vv** [comment]
1，使用 Get 方法读取池中连接出来，手动关闭它。这样可以减少池中的连接数量。
2，使用 ClearInvalidConnection 方法清除池中的死连接
